export { getDb } from './client'
export * from './dal/users'
export * from './dal/exercises'
export * from './dal/plans'
export * from './dal/workouts'
export * from './dal/planExercises'
export * from './dal/planTargets'
export * from './dal/sessions'
export * from './dal/sets'
export * from './dal/digestReports'
export { evictOldRecords } from './eviction'
